# Generated by Django 3.2.3 on 2021-06-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='image',
            field=models.ImageField(default='serie.png', upload_to='series/images'),
        ),
    ]
